build:
  version: "1.0"  

accounts:
  message: "Welcome to Account microservice related to prod environment"
  contactDetails:
    name: "Vipin prod lead"
    email: "vipin88@gmail.com"
  onCallSupport:
    -(555) 666 7777
    -(555) 666 8888    
