build:
  version: "3.0"  

accounts:
  message: "Welcome to Account microservice"
  contactDetails:
    name: "Vipin Tyagi"
    email: "vipinvats88@gmail.com"
  onCallSupport:
    -(555) 666 7777
    -(555) 666 8888    
