
build:
  version: "2.0"  

cards:
  message: "Welcome to qa Cards microservice"
  contactDetails:
    name: "Vipin Tyagi"
    email: "vipinvats88@gmail.com"
  onCallSupport:
    -(555) 666 7766
    -(555) 666 8877    
     
