
       
   build:
     version: "3.0"  

   cards:
     message: "Welcome to loan microservice"
     contactDetails:
       name: "Vipin Tyagi"
       email: "vipinvats88@gmail.com"
     onCallSupport:
      -(555) 666 7766
      -(555) 666 8877    
     

