server:
  port: 8071

encrypt:
  key: "4613SoJp4u5Vg5E7wkxf6g==" 

spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
          # search-locations: "classpath:/config"
          # search-locations: "file:///Users//eazybytes//Documents//config"
        git:
          uri: "https://github.com/vipinvats42/microservices-config.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
       # native:
         # search-locations: "classpath:/config"  
        #  search-locations: "file:///G://vscode-project-docker//docker-boot-project//microservice//server-location-config"
  rabbitmq:
    host: localhost
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"